name: 'Tests'


on:
  workflow_dispatch: # To can dispatch manually

  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - main


env:
  SDK_VERSION_6: '6.0.420'
  SDK_VERSION_5: '5.0.408'


jobs:

  test-project:
    name: "Test nuget"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: |
          ${{ env.SDK_VERSION_6 }}
          ${{ env.SDK_VERSION_5 }}

    - name: "Restore dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --configuration Release --no-restore

    - name: "Test"
      run: dotnet test --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed"
